almacenEmpresa/src/Entity/RegistroSalida.php
<?php

namespace App\Entity;

use App\Repository\RegistroSalidaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RegistroSalidaRepository::class)]
class RegistroSalida
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $cantidad = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_salida = null;

    /**
     * @var Collection<int, objetos>
     */
    #[ORM\OneToMany(targetEntity: objetos::class, mappedBy: 'relacionRegistroSalida')]
    private Collection $relacion;

    public function __construct()
    {
        $this->relacion = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCantidad(): ?int
    {
        return $this->cantidad;
    }

    public function setCantidad(int $cantidad): static
    {
        $this->cantidad = $cantidad;

        return $this;
    }

    public function getFechaSalida(): ?\DateTimeInterface
    {
        return $this->fecha_salida;
    }

    public function setFechaSalida(\DateTimeInterface $fecha_salida): static
    {
        $this->fecha_salida = $fecha_salida;

        return $this;
    }

    /**
     * @return Collection<int, objetos>
     */
    public function getRelacion(): Collection
    {
        return $this->relacion;
    }

    public function addRelacion(objetos $relacion): static
    {
        if (!$this->relacion->contains($relacion)) {
            $this->relacion->add($relacion);
            $relacion->setRelacionRegistroSalida($this);
        }

        return $this;
    }

    public function removeRelacion(objetos $relacion): static
    {
        if ($this->relacion->removeElement($relacion)) {
            // set the owning side to null (unless already changed)
            if ($relacion->getRelacionRegistroSalida() === $this) {
                $relacion->setRelacionRegistroSalida(null);
            }
        }

        return $this;
    }
}

almacenEmpresa/src/Form/RegistroSalidaType.php
<?php

namespace App\Form;

use App\Entity\RegistroSalida;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegistroSalidaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('cantidad')
            ->add('fecha_salida', null, [
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => RegistroSalida::class,
        ]);
    }
}

almacenEmpresa/src/Controller/RegistroSalidaController.php
<?php

namespace App\Controller;

use App\Entity\RegistroSalida;
use App\Form\RegistroSalidaType;
use App\Repository\RegistroSalidaRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/registro/salida')]
final class RegistroSalidaController extends AbstractController
{
    #[Route(name: 'app_registro_salida_index', methods: ['GET'])]
    public function index(RegistroSalidaRepository $registroSalidaRepository): Response
    {
        return $this->render('registro_salida/index.html.twig', [
            'registro_salidas' => $registroSalidaRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_registro_salida_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $registroSalida = new RegistroSalida();
        $form = $this->createForm(RegistroSalidaType::class, $registroSalida);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($registroSalida);
            $entityManager->flush();

            return $this->redirectToRoute('app_registro_salida_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('registro_salida/new.html.twig', [
            'registro_salida' => $registroSalida,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_registro_salida_show', methods: ['GET'])]
    public function show(RegistroSalida $registroSalida): Response
    {
        return $this->render('registro_salida/show.html.twig', [
            'registro_salida' => $registroSalida,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_registro_salida_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, RegistroSalida $registroSalida, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RegistroSalidaType::class, $registroSalida);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_registro_salida_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('registro_salida/edit.html.twig', [
            'registro_salida' => $registroSalida,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_registro_salida_delete', methods: ['POST'])]
    public function delete(Request $request, RegistroSalida $registroSalida, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$registroSalida->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($registroSalida);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_registro_salida_index', [], Response::HTTP_SEE_OTHER);
    }
}

almacenEmpresa/templates/registro_salida/_delete_form.html.twig
<form method="post" action="{{ path('app_registro_salida_delete', {'id': registro_salida.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ registro_salida.id) }}">
    <button class="btn">Delete</button>
</form>

almacenEmpresa/templates/registro_salida/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit RegistroSalida{% endblock %}

{% block body %}
    <h1>Edit RegistroSalida</h1>

    {{ include('registro_salida/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_registro_salida_index') }}">back to list</a>

    {{ include('registro_salida/_delete_form.html.twig') }}
{% endblock %}

almacenEmpresa/templates/registro_salida/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RegistroSalida index{% endblock %}

{% block body %}
    <h1>RegistroSalida index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cantidad</th>
                <th>Fecha_salida</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for registro_salida in registro_salidas %}
            <tr>
                <td>{{ registro_salida.id }}</td>
                <td>{{ registro_salida.cantidad }}</td>
                <td>{{ registro_salida.fechaSalida ? registro_salida.fechaSalida|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_registro_salida_show', {'id': registro_salida.id}) }}">show</a>
                    <a href="{{ path('app_registro_salida_edit', {'id': registro_salida.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_registro_salida_new') }}">Create new</a>
{% endblock %}

almacenEmpresa/templates/registro_salida/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New RegistroSalida{% endblock %}

{% block body %}
    <h1>Create new RegistroSalida</h1>

    {{ include('registro_salida/_form.html.twig') }}

    <a href="{{ path('app_registro_salida_index') }}">back to list</a>
{% endblock %}

almacenEmpresa/templates/registro_salida/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RegistroSalida{% endblock %}

{% block body %}
    <h1>RegistroSalida</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ registro_salida.id }}</td>
            </tr>
            <tr>
                <th>Cantidad</th>
                <td>{{ registro_salida.cantidad }}</td>
            </tr>
            <tr>
                <th>Fecha_salida</th>
                <td>{{ registro_salida.fechaSalida ? registro_salida.fechaSalida|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_registro_salida_index') }}">back to list</a>

    <a href="{{ path('app_registro_salida_edit', {'id': registro_salida.id}) }}">edit</a>

    {{ include('registro_salida/_delete_form.html.twig') }}
{% endblock %}