almacenEmpresa/src/Entity/Registro.php
<?php

namespace App\Entity;

use App\Repository\RegistroRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RegistroRepository::class)]
class Registro
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $cantidad = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_entrada = null;

    /**
     * @var Collection<int, objetos>
     */
    #[ORM\OneToMany(targetEntity: objetos::class, mappedBy: 'relacionRegistros')]
    private Collection $relacion;

    public function __construct()
    {
        $this->relacion = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCantidad(): ?int
    {
        return $this->cantidad;
    }

    public function setCantidad(int $cantidad): static
    {
        $this->cantidad = $cantidad;

        return $this;
    }

    public function getFechaEntrada(): ?\DateTimeInterface
    {
        return $this->fecha_entrada;
    }

    public function setFechaEntrada(\DateTimeInterface $fecha_entrada): static
    {
        $this->fecha_entrada = $fecha_entrada;

        return $this;
    }

    /**
     * @return Collection<int, objetos>
     */
    public function getRelacion(): Collection
    {
        return $this->relacion;
    }

    public function addRelacion(objetos $relacion): static
    {
        if (!$this->relacion->contains($relacion)) {
            $this->relacion->add($relacion);
            $relacion->setRelacionRegistros($this);
        }

        return $this;
    }

    public function removeRelacion(objetos $relacion): static
    {
        if ($this->relacion->removeElement($relacion)) {
            // set the owning side to null (unless already changed)
            if ($relacion->getRelacionRegistros() === $this) {
                $relacion->setRelacionRegistros(null);
            }
        }

        return $this;
    }
}

almacenEmpresa/src/Form/RegistroType.php
<?php

namespace App\Form;

use App\Entity\Registro;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegistroType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('cantidad')
            ->add('fecha_entrada', null, [
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Registro::class,
        ]);
    }
}

almacenEmpresa/src/Controller/RegistroController.php
<?php

namespace App\Controller;

use App\Entity\Registro;
use App\Form\RegistroType;
use App\Repository\RegistroRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/registro')]
final class RegistroController extends AbstractController
{
    #[Route(name: 'app_registro_index', methods: ['GET'])]
    public function index(RegistroRepository $registroRepository): Response
    {
        return $this->render('registro/index.html.twig', [
            'registros' => $registroRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_registro_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $registro = new Registro();
        $form = $this->createForm(RegistroType::class, $registro);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($registro);
            $entityManager->flush();

            return $this->redirectToRoute('app_registro_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('registro/new.html.twig', [
            'registro' => $registro,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_registro_show', methods: ['GET'])]
    public function show(Registro $registro): Response
    {
        return $this->render('registro/show.html.twig', [
            'registro' => $registro,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_registro_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Registro $registro, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RegistroType::class, $registro);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_registro_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('registro/edit.html.twig', [
            'registro' => $registro,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_registro_delete', methods: ['POST'])]
    public function delete(Request $request, Registro $registro, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$registro->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($registro);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_registro_index', [], Response::HTTP_SEE_OTHER);
    }
}

almacenEmpresa/templates/registro/_delete_form.html.twig
<form method="post" action="{{ path('app_registro_delete', {'id': registro.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ registro.id) }}">
    <button class="btn">Delete</button>
</form>

almacenEmpresa/templates/registro/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Registro{% endblock %}

{% block body %}
    <h1>Edit Registro</h1>

    {{ include('registro/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_registro_index') }}">back to list</a>

    {{ include('registro/_delete_form.html.twig') }}
{% endblock %}

almacenEmpresa/templates/registro/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Registro index{% endblock %}

{% block body %}
    <h1>Registro index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cantidad</th>
                <th>Fecha_entrada</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for registro in registros %}
            <tr>
                <td>{{ registro.id }}</td>
                <td>{{ registro.cantidad }}</td>
                <td>{{ registro.fechaEntrada ? registro.fechaEntrada|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_registro_show', {'id': registro.id}) }}">show</a>
                    <a href="{{ path('app_registro_edit', {'id': registro.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_registro_new') }}">Create new</a>
{% endblock %}

almacenEmpresa/templates/registro/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Registro{% endblock %}

{% block body %}
    <h1>Create new Registro</h1>

    {{ include('registro/_form.html.twig') }}

    <a href="{{ path('app_registro_index') }}">back to list</a>
{% endblock %}

almacenEmpresa/templates/registro/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Registro{% endblock %}

{% block body %}
    <h1>Registro</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ registro.id }}</td>
            </tr>
            <tr>
                <th>Cantidad</th>
                <td>{{ registro.cantidad }}</td>
            </tr>
            <tr>
                <th>Fecha_entrada</th>
                <td>{{ registro.fechaEntrada ? registro.fechaEntrada|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_registro_index') }}">back to list</a>

    <a href="{{ path('app_registro_edit', {'id': registro.id}) }}">edit</a>

    {{ include('registro/_delete_form.html.twig') }}
{% endblock %}